#!/bin/bash
cat TQQQ-M2.csv |\
awk '
    BEGIN {
        d    = "";
        high = 0;
        low  = 999999
    }
    {
        if (d!=$1) {
            if (high > 0) {
#print ""
                print(d "\t" open "\t"  high "\t" low "\t" prev);
#print "-------------\n";
            }
            d    = $1;
            open = $3
            high = 0;
            low  = 999999
        }
#print
        if ($3 > high)
            high=$3;
        if ($3 < low)
            low=$3;
        prev=$3;
    }
'

